TERMINOLOGY = {
	"VECTOR" : "This is a type of unit that is a product of a magnitude unit such as length and a displacement or directional unit such as angle, or directions in general.",
	"SCALAR" : "This is a type unit wherein the unit of the quantity is only the magnitude, one example is speed.",
	"QUADRATIC FORMULA" : "This formula is used to get the value of x when the highest degree of the equation is two, and most especially when it is not factorable.",
	"PERIMETER" : "It is the sum of all sides of the given polygon, such as rectangle, square, triangle, etc.",
	"AREA" : "It is the coverage value of a two dimensional shape. For example, to get the area of square, you must multiply the side to itself, or simply side squared.",
	"VOLUME" : "It is the computed capacity or space of a three-dimensional figure. For example, the volume of the cube can be computed by multiplying the sides to itself three times.",
	"DERIVATIVE" : "It is a mathematical process, known as y'' or dy/dx, it is used to get the change of the variable. It is also defined by the limit function.",
	"INTEGRAL" : "It is a mathematical process wherein you can get the area of a specific curve with respect to x. It is also called an anti-derivative.",
	"RATIO" : "It is to divide and proportionate a value of a length from a big perspective to a small perspective. This is commonly used in Engineering Drawing.",
	"L'HOPITALS RULE" : "It is used to do a derivative to certain rational algebraic expression where the numerator and the denominator is both zero.",
	"TRIGONOMETRY" : "This are mainly composed of what is commonly known as SOH CAH TOA. it is used to find the vales of an angle and missing sides of a right triangle.",
	"NATURAL LOG" : "It is notated as y = ln x. This is commonly used in business, graphs, economy, inflation, population of an area, etc.",
	"PI" : "It is a constant that represents how many radii it would take to enclose a circle. The approximate value is 3.1415.",
	"E" : "It is a constant to where it is the opposite of natural log. This is mainly used in growth or decay problems. The approximate vale ia 2.7182.",
	"G" : "It is the gravitational acceleration of a certain celestial body. Our earth has a gravitational acceleration of 9.81m/s^2.",
	"SURFACE AREA" : "It is the computed area on all of the surface of a three-dimensional figure. For example, when you are trying to get the volume of a cylinder, you must use four-thirds multiplied by pi and radius cubed.",
	"INERTIA" : "This is the Newton's First Law of Motion where it states that an object will be at rest unless you apply force on it.",
	"ACCELERATION" : "This is Newton's Second Law of Motion which states that the rate of change of momentum of an object is directly proportional to the unbalanced force in the direction of force.",
	"INTERACTION" :  "This is Newton's Third Law of Motion, wherein it states that for every action, there's an equal and opposite reaction.",
	"SQUARE ROOT" : "This symbol is used to compute for the sides when the only given is the area of a two dimensional figure.",
	"POLYNOMIAL" : "It is an equation to where it is the number of terms in an equation is higher than three, and the highest degree must be two.",
	"T-SQUARE" : "It is a tool used by Engineers when creating a architectural plate or a layout. This is commonly used to do single strokes of lines and make straight and accurate measurements.",
	"PROTRACTOR" : "It is a tool to where you measure and draw a specific angle. It is commonly used in all aspects of engineering such as in Calculus, Physics, Geometry, etc.",
	"METER" : "It is the base unit of length. It's symbol is represented as m.",
	"KELVIN" : "It is the base unit of temperature. It's symbol is represented as K.",
	"KILOGRAM" : "It is the base unit of mass. It's symbol is represented as kg.",
	"CANDELA" : "It is the base unit of light intensity. It's symbol is represented as Ca.",
	"SECOND" : "It is the base unit of time. It's symbol is represented as s.",
	"MOLE" : "It is the base unit of mass per material. It's symbol is represented as mol.",
	"AMPERE" : "It is the base unit of electric current. It's symbol is represented as A.",
	}
x = input ("Hi, I'm the Engineering Dictionary! What word do you want to know that is related to engineering?")
print(TERMINOLOGY[x])